export const DATE_FORMATS_DEFAULT = 'YYYY/MM/DD';
export const TIME_FORMATS_DEFAULT = 'HH:mm:ss';
export const FORMATS_DEFAULT_MAP = {
  date: DATE_FORMATS_DEFAULT,
  year: 'YYYY',
  month: 'YYYY/MM',
  week: 'YYYY/MM/DD',
  datetime: `${DATE_FORMATS_DEFAULT} HH:mm`,
  dateminutes: `${DATE_FORMATS_DEFAULT} HH:mm`,
  dateseconds: `${DATE_FORMATS_DEFAULT} ${TIME_FORMATS_DEFAULT}`,
  daterange: 'YYYY/MM/DD',
  datetimerange: `${DATE_FORMATS_DEFAULT} HH:mm`,
  dateminutesrange: `${DATE_FORMATS_DEFAULT} HH:mm`,
  datesecondsrange: `${DATE_FORMATS_DEFAULT} ${TIME_FORMATS_DEFAULT}`,
  monthrange: 'YYYY/MM',
  yearrange: 'YYYY',
  time: 'HH:mm',
  minutes: 'HH:mm',
  seconds: TIME_FORMATS_DEFAULT,
};
export const LOCALES_DEFAULT_FORMATS = {
  En: {
    date: 'DD/MM/YYYY',
    year: 'YYYY',
    month: 'MMM YYYY',
    week: 'DD/MM/YYYY',
    datetime: 'DD/MM/YYYY, HH:mm',
    dateminutes: 'DD/MM/YYYY, HH:mm',
    dateseconds: `DD/MM/YYYY, ${TIME_FORMATS_DEFAULT}`,
    daterange: 'DD/MM/YYYY',
    datetimerange: 'DD/MM/YYYY, HH:mm',
    dateminutesrange: 'DD/MM/YYYY, HH:mm',
    datesecondsrange: `DD/MM/YYYY, ${TIME_FORMATS_DEFAULT}`,
    monthrange: 'MMM YYYY',
    yearrange: 'YYYY',
    time: 'HH:mm',
    minutes: 'HH:mm',
    seconds: TIME_FORMATS_DEFAULT,
  },
  ZhCN: FORMATS_DEFAULT_MAP,
  ZhTW: FORMATS_DEFAULT_MAP,
  SvSE: FORMATS_DEFAULT_MAP,
};
